<div class="media">
	<a class="pull-left" href="#"> <img class="media-object"
		data-src="holder.js/64x64">
	</a>
	<div class="media-body">
		<h4 class="media-heading">Media heading</h4>
		<p>aksdjfhkajlsdhfkjasdhfkjh</p>
	</div>
</div>

<div class="media">
	<a class="pull-left" href="#"> <img class="media-object"
		data-src="holder.js/64x64">
	</a>
	<div class="media-body">
		<h4 class="media-heading">Media heading</h4>
		<p>aksdjfhkajlsdhfkjasdhfkjh</p>
	</div>
</div>

<ul class="media-list">
  <li class="media well well-small">
    <a class="pull-left" href="#">
      <img class="media-object" data-src="holder.js/64x64">
    </a>
    <div class="media-body">
      <h4 class="media-heading">Media heading</h4>
      ...
 
      <!-- Nested media object -->
      <div class="media">
        ...
     </div>
    </div>
  </li>
   <li class="media well well-small">
    <a class="pull-left" href="#">
      <img class="media-object" data-src="holder.js/64x64">
    </a>
    <div class="media-body">
      <h4 class="media-heading">Media heading</h4>
      ...
 
      <!-- Nested media object -->
      <div class="media">
        ...
     </div>
    </div>
  </li>
</ul>