<?php echo $this->doctype("XHTML1_STRICT"); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php

echo $this->headMeta();
echo $this->headTitle();
/*
 $this->headLink(array('rel' => 'icon', 'type'=>'image/x-icon', 'href' =>
 	$this->baseUrl('/public/images/favicon.ico')), 'PREPEND');
 */
$this->headLink()->appendStylesheet(
		$this->baseUrl('/public/css/main.css'),
		'screen');
$this->headLink()->appendStylesheet(
		$this->baseUrl('/public/js_css_plugins/bootstrap/css/bootstrap.min.css'),
		'screen');
$this->headLink()->appendStylesheet(
		$this->baseUrl('/public/js_css_plugins/jquery_ui/theme/jquery-ui-1.9.2.css'),
		'screen');
$this->headLink()->appendStylesheet(
		$this->baseUrl('/public/js_css_plugins/custom_search/jquery.autocomplete.css'),
		'screen');

$this->headLink()->appendStylesheet(
		$this->baseUrl('/public/css/style.css'),
		'screen');

$this->headScript()->appendFile(
		$this->baseUrl('/public/js/jquery-1.8.3.min.js'));
$this->headScript()->appendFile(
		$this->baseUrl('/public/js_css_plugins/spin/spin.min.js'));
$this->headScript()->appendFile(
		$this->baseUrl('/public/js_css_plugins/bootstrap/js/bootstrap.min.js'));
$this->headScript()->appendFile(
		$this->baseUrl('/public/js_css_plugins/jquery_ui/jquery-ui-1.9.2.min.js'));
$this->headScript()->appendFile(
		$this->baseUrl('/public/js_css_plugins/jquery_ui/jquery.ui.touch-punch.min.js'));
$this->headScript()->appendFile(
		$this->baseUrl('/public/js_css_plugins/custom_search/jquery.autocomplete.js'));

$this->headScript()->appendFile(
		$this->baseUrl('/public/js/my_js_functional.js'));

echo $this->headLink ();
echo $this->headScript();

$this->headLink()->exchangeArray(array());
$this->headScript()->exchangeArray(array());
?>
</head>
<body>
	<div class="navbar  navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		        </button> 
				
				<a class="brand" href="<?php echo $this->url(array('action'=>'home'),'my_default_route',true); ?>">
					<img alt="" src="<?php echo $this->baseUrl('/public/images/logo-for-site.png') ?> ">
				</a>
				<?php 
						if(Zend_Session::namespaceIsset('Zend_User_Login')):
						    $user_info = Zend_Session::namespaceGet('Zend_User_Login');
						    $user_params = $user_info['users_params'];						    
					?>
    					<div class="btn-group pull-right">
    						 <button class="btn">
    						 	<i class="icon-user"></i>
    						 	<?php echo $user_params->username; ?>
    						 </button>
							  <button class="btn dropdown-toggle" data-toggle="dropdown">
							    <span class="caret"></span>
							  </button>
    						<ul class="dropdown-menu">
    							<li><a href="<?php echo $this->url(array('action'=>'edituserinfo'),null,true) ?>"><i class="icon-pencil"></i> Edit</a></li>
    							<li class="divider"></li>
    							<li><a href="<?php echo $this->url(array('action'=>'logout'),null,true) ?>"><i class="icon-off"></i> Log Out </a></li>
    						</ul>
    					</div>
    					
					<?php endif; ?>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li class="active">
			                <a href="<?php echo $this->url(array('action'=>'home'),'my_default_route',true); ?>">Home</a>
			            </li>
						<li class="dropdown">
						    <a href="#" class="dropdown-toggle"
							data-toggle="dropdown">Dropdown <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li class="nav-header">Nav header</li>
								<li><a href="#">Separated link</a></li>
								<li class="dropdown-submenu">
									<a href="#">More</a>
									<ul class="dropdown-menu">
										<li><a href="#">Something else here</a></li>
										<li><a href="#">Action</a></li>
										<li><a href="#">Another action</a></li>
										<li><a href="#">Something else here</a></li>
									</ul>
								</li>
							</ul>
						</li>
						
					</ul>
					
				</div>
				<!--/.nav-collapse -->
			</div>
		</div>
	</div>
	<div class="container-fluid">
	  <div class="row-fluid">
		<div class="span3">
			<div class="well sidebar-nav sidebar-nav-fixed">
				<ul class="nav nav-list">
					<li class="nav-header">Sidebar</li>
					<li class="dropdown-submenu">
						<a href="#">Dropdown</a>
						<ul class="dropdown-menu">
							<li><a href="#">6565</a></li>
							<li><a href="#">2sw</a></li>
							<li><a href="#">eqwr</a></li>
							<li><a href="#">erhf</a></li>
						</ul> 
					</li>
					<li> <a href="#">Dropsadasddown</a> </li>
					<li> <a href="#">efd596</a> </li>
					<li> <a href="#">easf</a> </li>
					<li> <a href="#">Droasdfpdown</a> </li>
				</ul>
			</div>
		</div>
		<div class="span9">
	     <?php echo $this->layout()->content; ?>
	    </div>
	    </div>
	</div>
	<footer>footer</footer>
	 <input type="hidden" id="mydate" value="<?php echo date('m-d-Y'); ?>"/>
</body>
</html>